name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - master  # تغییر به شاخه master

jobs:
  build:
    runs-on: ubuntu-latest  # استفاده از سرورهای لینوکس برای اجرا

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # بررسی کد پروژه از گیت‌هاب

      - name: Build Docker image
        run: docker build -t reza/shop-ketab-khoob -f Shop.RestApi/dockerfile/Dockerfile .  # ساخت ایمیج Docker

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  # لاگین به Docker Hub

      - name: Push Docker image to Docker Hub
        run: docker push reza/shop-ketab-khoob  # ارسال ایمیج به Docker Hub

